name: Test schedule DPV

on:
  schedule:
    # Prueba temporal: minutos concretos, cada 10 minutos
    - cron: "3,13,23,33,43,53 * * * *"

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar hora UTC
        run: |
          echo "Prueba de ejecución automática"
          date -u
